// SEARCH
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const RESET_SEARCH_QUERY = 'RESET_SEARCH_QUERY';
export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT';
export const SET_SEARCH_ERROR = 'SET_SEARCH_ERROR';
export const SET_SEARCH_COMPLETED = 'SET_SEARCH_COMPLETED';
// SHOW MORE BUTTON
export const SET_JOKES_ON_PAGE = 'SET_JOKES_ON_PAGE'
export const RESET_JOKES_ON_PAGE = 'RESET_JOKES_ON_PAGE'
// LOADING
export const SET_LOADING = 'SET_LOADING'
// PAGINATION 
export const SET_PAGINATION_SETTINGS = 'SET_PAGINATION_SETTINGS';
export const RESET_PAGINATION_SETTINGS = 'RESET_PAGINATION_SETTIGS'
// RANDOM JOKE
export const SET_RANDOM_JOKE = 'SET_RANDOM_JOKE'